export const FOOD_DATABASE = {
  desayuno: [
    { nombre: 'Huevos revueltos con pan integral', kcal: 155, proteinas: 10, carbohidratos: 14, grasas: 7 },
    { nombre: 'Tortilla francesa con tostada', kcal: 140, proteinas: 10, carbohidratos: 10, grasas: 6 },
    { nombre: 'Yogur griego con avena y frutos rojos', kcal: 130, proteinas: 7, carbohidratos: 16, grasas: 4 },
    { nombre: 'Batido de proteína con plátano', kcal: 95, proteinas: 8, carbohidratos: 12, grasas: 1.5 },
    { nombre: 'Pan integral con aguacate y huevo', kcal: 180, proteinas: 7, carbohidratos: 14, grasas: 11 },
    { nombre: 'Gachas de avena con manzana y canela', kcal: 120, proteinas: 5, carbohidratos: 20, grasas: 2.5 },
    { nombre: 'Tostada de queso fresco y tomate', kcal: 110, proteinas: 6, carbohidratos: 13, grasas: 4 },
    { nombre: 'Crepes de avena con miel', kcal: 160, proteinas: 7, carbohidratos: 24, grasas: 4 },
    { nombre: 'Bowl de quinoa con frutas', kcal: 140, proteinas: 5, carbohidratos: 22, grasas: 4 },
    { nombre: 'Huevo pochado con espinacas y pan', kcal: 120, proteinas: 8, carbohidratos: 9, grasas: 5 },
    { nombre: 'Batido de avena y frutos secos', kcal: 140, proteinas: 6, carbohidratos: 16, grasas: 6 },
    { nombre: 'Pan tostado con jamón serrano', kcal: 160, proteinas: 9, carbohidratos: 14, grasas: 8 },
  ],
  comida: [
    { nombre: 'Pollo a la plancha con arroz y ensalada', kcal: 130, proteinas: 11, carbohidratos: 13, grasas: 3 },
    { nombre: 'Salmón al horno con patatas y verduras', kcal: 140, proteinas: 11, carbohidratos: 12, grasas: 5 },
    { nombre: 'Lentejas guisadas con arroz', kcal: 120, proteinas: 7, carbohidratos: 17, grasas: 3 },
    { nombre: 'Ensalada de quinoa con pollo', kcal: 130, proteinas: 9, carbohidratos: 12, grasas: 5 },
    { nombre: 'Pollo al curry con arroz basmati', kcal: 150, proteinas: 11, carbohidratos: 17, grasas: 4 },
    { nombre: 'Pasta integral con atún y tomate', kcal: 140, proteinas: 9, carbohidratos: 19, grasas: 3 },
    { nombre: 'Bowl de carne magra y boniato', kcal: 130, proteinas: 12, carbohidratos: 13, grasas: 3.5 },
    { nombre: 'Merluza a la plancha con puré de patata', kcal: 120, proteinas: 10, carbohidratos: 12, grasas: 3 },
    { nombre: 'Garbanzos con espinacas y arroz', kcal: 125, proteinas: 7, carbohidratos: 18, grasas: 3 },
    { nombre: 'Fajitas de ternera con pimientos', kcal: 150, proteinas: 11, carbohidratos: 15, grasas: 5 },
    { nombre: 'Quinoa con verduras y huevo', kcal: 135, proteinas: 7, carbohidratos: 16, grasas: 5 },
    { nombre: 'Arroz con pollo y verduras', kcal: 125, proteinas: 9, carbohidratos: 16, grasas: 3 },
  ],
  merienda: [
    { nombre: 'Yogur griego con frutos secos', kcal: 160, proteinas: 8, carbohidratos: 10, grasas: 10 },
    { nombre: 'Manzana con mantequilla de cacahuete', kcal: 150, proteinas: 4, carbohidratos: 16, grasas: 8 },
    { nombre: 'Batido de frutas y avena', kcal: 90, proteinas: 4, carbohidratos: 16, grasas: 1.5 },
    { nombre: 'Pan integral con jamón', kcal: 180, proteinas: 11, carbohidratos: 18, grasas: 7 },
    { nombre: 'Queso cottage con piña', kcal: 80, proteinas: 9, carbohidratos: 6, grasas: 2 },
    { nombre: 'Barrita de avena y miel', kcal: 380, proteinas: 8, carbohidratos: 60, grasas: 12 },
    { nombre: 'Hummus con bastones de zanahoria', kcal: 130, proteinas: 5, carbohidratos: 12, grasas: 7 },
    { nombre: 'Tostada con aguacate', kcal: 180, proteinas: 4, carbohidratos: 16, grasas: 11 },
    { nombre: 'Batido de chocolate y proteína', kcal: 110, proteinas: 12, carbohidratos: 12, grasas: 2 },
    { nombre: 'Yogur natural con nueces y miel', kcal: 140, proteinas: 6, carbohidratos: 13, grasas: 7 },
    { nombre: 'Sandwich de pavo y queso', kcal: 150, proteinas: 10, carbohidratos: 15, grasas: 5 },
    { nombre: 'Requesón con fresas', kcal: 85, proteinas: 9, carbohidratos: 7, grasas: 2 },
  ],
  cena: [
    { nombre: 'Ensalada de atún con huevo', kcal: 120, proteinas: 10, carbohidratos: 5, grasas: 7 },
    { nombre: 'Tortilla de calabacín', kcal: 110, proteinas: 7, carbohidratos: 5, grasas: 7 },
    { nombre: 'Crema de calabaza con pollo', kcal: 90, proteinas: 6, carbohidratos: 9, grasas: 3 },
    { nombre: 'Ensalada de pollo a la plancha', kcal: 110, proteinas: 12, carbohidratos: 6, grasas: 4 },
    { nombre: 'Verduras salteadas con tofu', kcal: 100, proteinas: 7, carbohidratos: 8, grasas: 5 },
    { nombre: 'Ensalada de garbanzos y atún', kcal: 140, proteinas: 9, carbohidratos: 14, grasas: 5 },
    { nombre: 'Sopa de verduras con queso', kcal: 70, proteinas: 4, carbohidratos: 7, grasas: 3 },
    { nombre: 'Pechuga de pavo con ensalada', kcal: 100, proteinas: 13, carbohidratos: 5, grasas: 3 },
    { nombre: 'Huevos al horno con espinacas', kcal: 130, proteinas: 10, carbohidratos: 4, grasas: 9 },
    { nombre: 'Coliflor al horno con queso', kcal: 120, proteinas: 8, carbohidratos: 7, grasas: 7 },
    { nombre: 'Salmón a la plancha con espárragos', kcal: 140, proteinas: 14, carbohidratos: 3, grasas: 8 },
    { nombre: 'Tortilla de patata ligera', kcal: 140, proteinas: 6, carbohidratos: 13, grasas: 7 },
  ],
};
